// Package store persists miles cards in PostgreSQL.
package store

import (
	"database/sql"
	"errors"
	"fmt"
	"time"

	_ "github.com/jackc/pgx/v5/stdlib"
)

// Card is a single tracked credit card.
type Card struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Bank   string `json:"bank"`
	Miles  int    `json:"miles"`
	Last4  string `json:"last4"`
	Expiry string `json:"expiry"` // YYYY-MM-DD
}

// ErrNotFound is returned when a card id does not exist.
var ErrNotFound = errors.New("card not found")

// Store is a PostgreSQL-backed collection of cards.
type Store struct {
	db *sql.DB
}

// New connects to the database at dsn, ensures the schema exists, and seeds
// demo data when the table is empty.
func New(dsn string) (*Store, error) {
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return nil, fmt.Errorf("open db: %w", err)
	}
	db.SetMaxOpenConns(10)
	db.SetConnMaxLifetime(time.Hour)
	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("ping db: %w", err)
	}
	s := &Store{db: db}
	if err := s.migrate(); err != nil {
		return nil, err
	}
	if err := s.seedIfEmpty(); err != nil {
		return nil, err
	}
	return s, nil
}

// Close releases the underlying connection pool.
func (s *Store) Close() error { return s.db.Close() }

func (s *Store) migrate() error {
	_, err := s.db.Exec(`
		CREATE TABLE IF NOT EXISTS cards (
			id     UUID PRIMARY KEY DEFAULT gen_random_uuid(),
			name   TEXT NOT NULL,
			bank   TEXT NOT NULL,
			miles  INTEGER NOT NULL DEFAULT 0,
			last4  TEXT NOT NULL DEFAULT '',
			expiry DATE NOT NULL
		)`)
	return err
}

// List returns all cards.
func (s *Store) List() ([]Card, error) {
	rows, err := s.db.Query(`SELECT id::text, name, bank, miles, last4, to_char(expiry,'YYYY-MM-DD') FROM cards ORDER BY expiry`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	out := []Card{}
	for rows.Next() {
		var c Card
		if err := rows.Scan(&c.ID, &c.Name, &c.Bank, &c.Miles, &c.Last4, &c.Expiry); err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// Create inserts a new card; the id is generated by PostgreSQL and returned.
func (s *Store) Create(c Card) (Card, error) {
	err := s.db.QueryRow(
		`INSERT INTO cards (name, bank, miles, last4, expiry) VALUES ($1,$2,$3,$4,$5) RETURNING id::text`,
		c.Name, c.Bank, c.Miles, c.Last4, c.Expiry,
	).Scan(&c.ID)
	if err != nil {
		return Card{}, err
	}
	return c, nil
}

// Update replaces fields of the card with the given id.
func (s *Store) Update(id string, c Card) (Card, error) {
	res, err := s.db.Exec(
		`UPDATE cards SET name=$2, bank=$3, miles=$4, last4=$5, expiry=$6 WHERE id=$1::uuid`,
		id, c.Name, c.Bank, c.Miles, c.Last4, c.Expiry,
	)
	if err != nil {
		return Card{}, err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return Card{}, ErrNotFound
	}
	c.ID = id
	return c, nil
}

// Delete removes the card with the given id.
func (s *Store) Delete(id string) error {
	res, err := s.db.Exec(`DELETE FROM cards WHERE id=$1::uuid`, id)
	if err != nil {
		return err
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return ErrNotFound
	}
	return nil
}

func (s *Store) seedIfEmpty() error {
	var n int
	if err := s.db.QueryRow(`SELECT COUNT(*) FROM cards`).Scan(&n); err != nil {
		return err
	}
	if n > 0 {
		return nil
	}
	for _, c := range seed() {
		if _, err := s.Create(c); err != nil {
			return err
		}
	}
	return nil
}

func seed() []Card {
	iso := func(days int) string {
		return time.Now().AddDate(0, 0, days).Format("2006-01-02")
	}
	return []Card{
		{Name: "Skyward Elite", Bank: "Nova Union", Miles: 67200, Last4: "5560", Expiry: iso(9)},
		{Name: "Voyage Infinite", Bank: "Aurora Bank", Miles: 48500, Last4: "4821", Expiry: iso(24)},
		{Name: "Platinum Rewards", Bank: "Meridian Financial", Miles: 120300, Last4: "0934", Expiry: iso(62)},
		{Name: "Everyday Travel", Bank: "Atlas Federal", Miles: 23800, Last4: "7715", Expiry: iso(156)},
		{Name: "Horizon Cash+", Bank: "Cobalt Trust", Miles: 15040, Last4: "2287", Expiry: iso(305)},
	}
}
